### ISSUE TITLE
Add Country to city list

### ISSUE THREAD

**Issue by qwertzui11** [bmaroti9/Overmorrow#1]
Great app! thx for making it!

When I search for `Vienna` I get three identical entries.
May I suggest that you add the Country/State to the list.

Eg I was interested into Vienna, the capital of Austria.

Thx for your time,
Cheers,
Markus

**Comment by bmaroti9** [comment]
Hi, Markus! 
Thank for reporting this problem. i have fixed it in version 2.0.3!

![Screenshot_20231227_165826](https://github.com/bmaroti9/Overmorrow/assets/101268206/88a98fc0-ae50-4b6e-b290-0fe270055f06)

Cheers,
Balint
