### ISSUE TITLE
Status for Last Checked?

### ISSUE THREAD

**Issue by hl2guide** [bmaroti9/Overmorrow#12]
Please consider showing the status of "last checked": e.g. 1m ago

**Comment by bmaroti9** [comment]
I have thought about it. but the thing that always keeps me back from actually doing it is (this might sound stupid) the fact that i have no idea where it should be placed. i have tried multiple places, but the cleanness of the main screen kind of feels ruined if i place any text there. I don't know. Just curious, where would you wan't to place it?

**Comment by hl2guide** [comment]
> I have thought about it. but the thing that always keeps me back from actually doing it is (this might sound stupid) the fact that i have no idea where it should be placed. i have tried multiple places, but the cleanness of the main screen kind of feels ruined if i place any text there. I don't know. Just curious, where would you wan't to place it?

I'd suggest that you have a look at Breezy Weather app (https://github.com/breezy-weather/breezy-weather) for inspiration.

If cleanness is the priority maybe simply show it on the settings page? Keep up the great work..

**Comment by bmaroti9** [comment]
How about this? i think this still looks clean, and it disappears after 4 seconds.

https://github.com/bmaroti9/Overmorrow/assets/101268206/0f528a50-3364-4169-9b39-e7323abffbec

**Comment by bmaroti9** [comment]
The last checked indicator is now added in v2.3.10.
