### ISSUE TITLE
[Feature Request/UI] rearrange elements

### ISSUE THREAD

**Issue by deathblade666** [bmaroti9/Overmorrow#13]
I think it'd be a real QoL feature to have the ability to rearrange the data sections. For example, personally I'd like to have the today's forecast at the top instead of under the radar.

**Comment by bmaroti9** [comment]
Hmm, i have heard this request multiple times now, so i guess I should implement it!
Some quick questions though: should it be choosing the layout from several presets or should it be a drag and drop system where you could completely set the order? Is is it good if the 3 more detailed days are together, right? like you wouldn't want to have for example the today part in a different place than the other two?

**Comment by BloodRaven0** [comment]
+1 drag and drop, with the ability to hide sections you dont need would be awesome!

**Comment by bmaroti9** [comment]
Hi! It's been a long time. I originally wanted this to be in v2.4.1, but i decided against it, but now i'm doing it.

https://github.com/user-attachments/assets/b0424937-c143-4ba8-9811-167555489ef1

i will say that all the widgets were sized and colored, and generally designed to look good around the other widgets in the original layout, so I can't guarantee that they look very good, but yeah, if you want you can reorder it now.

**Comment by bmaroti9** [comment]
available in v2.4.2

**Comment by bmaroti9** [comment]
Reopened due to requests to hide elements. #37

**Comment by bmaroti9** [comment]
#41
