### ISSUE TITLE
times radar map??

### ISSUE THREAD

**Issue by Marcopolos51** [bmaroti9/Overmorrow#16]
wonderful application, congratulations!!

Is it possible to add times to the Rainfall Radar map?

**Comment by bmaroti9** [comment]
This is one of those issues i am aware of, and i know a lot of people saying it as well, but for which i am kind of lazy to do because i would probably have to redesign the whole radar page. but of course it's possible, and if i find time i will definitely do it :)

**Comment by Marcopolos51** [comment]
Thanks 👍

**Comment by bmaroti9** [comment]
Hi! this is what i came up with. this is part of the material-you redesign i am doing now #22.

https://github.com/user-attachments/assets/61d772f1-4cca-416a-9912-3be47c31c2dd


https://github.com/user-attachments/assets/6de7cd63-38a3-4f11-94a6-e139c1eff716

**Comment by Marcopolos51** [comment]
great.  very good development of the application.  very good work.  looking forward to trying it.👍

**Comment by deathblade666** [comment]
> Hi! this is what i came up with. this is part of the material-you redesign i am doing now #22.
> 
> 
> 
> https://github.com/user-attachments/assets/61d772f1-4cca-416a-9912-3be47c31c2dd
> 
> 
> 
> 
> 
> https://github.com/user-attachments/assets/6de7cd63-38a3-4f11-94a6-e139c1eff716
> 
> 
> 
> 

Not sure if you'd prefer a separate issue for this but kinda in line with this one, a friend had requested i put in an issue on their behalf, Would it be too much trouble setting the default frame of the radar (before you press play) to the current frame then when you press play start from the beginning and play through? According to them most other weather apps have it set this way.

Thanks for all the hard work!

**Comment by bmaroti9** [comment]
https://github.com/user-attachments/assets/ade4e9b9-ffb4-440a-bf8f-d9104a8b5747

so like this right?

**Comment by deathblade666** [comment]
> Screencast.from.2024-08-16.16-47-24.mp4
> 
> so like this right?

Yep, looks good to me :)

**Comment by Marcopolos51** [comment]
yes, absolutely. it's great. you've done a great job! thank you

**Comment by bmaroti9** [comment]
available with the v2.4.1 release
