### ISSUE TITLE
The daily list does not load on the new version

### ISSUE THREAD

**Issue by dimostheenis** [bmaroti9/Overmorrow#17]
![Screenshot_20240602-220248](https://github.com/bmaroti9/Overmorrow/assets/76966291/ed6875f2-f2b3-412d-85d8-f0b35efd614a)
![Screenshot_20240602-220019](https://github.com/bmaroti9/Overmorrow/assets/76966291/79d75643-8014-434a-9d7f-acf2632780cc)

**Comment by bmaroti9** [comment]
That is because the weather provider is set to wearherpi. Wearherpi doesn't have daily.
