### ISSUE TITLE
Expand and contract days after overmorrow

### ISSUE THREAD

**Issue by BloodRaven0** [bmaroti9/Overmorrow#19]
Hey, first of all I'd like to say that I absolutely love this app, it's the most beautiful, sleek and well-made open source weather app I've seen. It gives the ad-ridden garbage produced by companies in the playstore a run for their money. The fact you made this at 15 is mindboggling. There is serious potential in you, keep working at your craft!

I have a small question/feature request.
I noticed that some days are expanded to show rain amounts throughout the day, while others are not. Would it be possible to have an option to have them all contracted by default, expanding/contracting when you tap them? Currently the rainy days take too much vertical space.

**Comment by bmaroti9** [comment]
First of all, thank you so much for the encouraging and positive words! 
Are you talking about the rain charts in the today, tomorrow, overmorrow screens, or the daily screen?
For the daily screen, i was thinking of actually doing the tapping expand/contract, but i tried adding these downward arrow at the end of each row, but it looked kind of stupid between the two lines of the data and the box of the daily, so i gave up on it. I also thought about clicking on it regularly, but i thought that it wouldn't be very intuitive and the average user wouldn't even realize you could do that... 
I though of making a setting to control when you want to see the rain chart. so for example if it above x mm of rain. and if you didn't want to see it, then just pull the slider all the way and it would say 'never'.
Please share your thoughts!

**Comment by BloodRaven0** [comment]
Yeah, a slider could work fine, but it would still be nice to be able to tap a rainy day (they are colored darker)  to still see its rain chart regardless of the slider setting. Or to hide a shown rainchart.

**Comment by bmaroti9** [comment]
Hi! it has been a long time, but as part of my material-you redesign #22, this is what i came up with.

https://github.com/user-attachments/assets/1561a4b9-c778-47e8-8d48-43522b1a4273

**Comment by BloodRaven0** [comment]
Looks pretty awesome, great job! ❤️

**Comment by bmaroti9** [comment]
available with the 2.4.1 version.
