### ISSUE TITLE
[Feature Request] Plugin support

### ISSUE THREAD

**Issue by knasiotis** [bmaroti9/Overmorrow#20]
Instead of hard coding data fetches from every known weather provider, allow for providers to be imported as plugins. Tachiyomi (now Mihon) should have an implementation of this feature (for other purposes ofc).
The benefit of this would be that the weight of the implementation gets off your shoulders and we could design implementations such as  web scrapers to connect overmorrow with our local weather providers.

**Comment by bmaroti9** [comment]
Wow, this is a pretty ambitious issue!
Designing a fully functional plugin system would be very challenging and time consuming for me, and i feel there are much more pressing problems that need to be fixed, and feature to be implemented. I have no idea how i would even start building that, i would need servers, and all kinds of stuff. I have no experience in any of that. :(
Even say if I could do it, I wouldn't want to have a full plugin system built just to have 4 plugins actually made for it. 
(sorry if i'm underestimating you guys but i don't the community is yet big enough for this)
I would much rather for your to just make a pull request and i will happily merge your local weather provider.
If we get to say 10 hard coded implementations, then we can start thinking about a plugin system.

**Comment by bmaroti9** [comment]
I've thought about it, and there are no plans to add plugins. You can still make a pull request with you provider.
