### ISSUE TITLE
Precipitation amount limit to 1 or 2 decimal places

### ISSUE THREAD

**Issue by deathblade666** [bmaroti9/Overmorrow#24]
I just installed the Newest version released today, first off. AMAZING WORK!!!. I noticed a minor bug with the precipitation amount. It shows the amount is 0.011811029999999998 in. Only in one spot tho thus far. 

This is under the Today metrics

![image](https://github.com/user-attachments/assets/dc90e4e3-8159-45bd-bbe5-7b87860dfb93)

Thanks you for all your hard work!!

**Comment by bmaroti9** [comment]
fixed in v2.4.2.
