### ISSUE TITLE
Small UI bug

### ISSUE THREAD

**Issue by serrq** [bmaroti9/Overmorrow#27]
OnePlus CPH2399
Android 14
Overmorrow 2.4.1

![1000118229](https://github.com/user-attachments/assets/6af47505-cccb-4597-af84-e131d11a15cb)

**Comment by bmaroti9** [comment]
Hi! Thanks for reporting this as well! I don't know why but i made the box for the texts a fixed height, and i guess with bigger font sizes it clips it. I have removed the fixed height.
It should be fixed with next update

**Comment by bmaroti9** [comment]
fixed in v2.4.2!
