### ISSUE TITLE
Wrong sunset

### ISSUE THREAD

**Issue by serrq** [bmaroti9/Overmorrow#28]
Weather provider: openmeteo

![1000118235](https://github.com/user-attachments/assets/09aa24db-339d-47c6-bafd-4ee3271a022c)

**Comment by bmaroti9** [comment]
Hi!
You're totally right. in the 24 hour time converting i accidentally wrote sunrise instead of sunset. I don't know how i didn't spot this already. Thank you! It will be fixed in the next version

**Comment by bmaroti9** [comment]
Also a bug. Also noticed and fixed

**Comment by bmaroti9** [comment]
fixed in v2.4.2!
