### ISSUE TITLE
Issue with Open-Meteo 

### ISSUE THREAD

**Issue by ak47m91** [bmaroti9/Overmorrow#30]
![Screenshot_20240903_133932.jpg](https://github.com/user-attachments/assets/8e6db7ed-5296-433f-a3ad-d3b88bafcdbb)

**Comment by bmaroti9** [comment]
Hey! HttpException 429 means, that you made waaay to many requests and the servers blocked you.
![image](https://github.com/user-attachments/assets/3f0462a9-e41f-49dd-b410-25378b4b7a70)
There is not much i can do about this. I personally have never run into this error even though testing with up to 50 cities.

**Comment by ak47m91** [comment]
Well , I barrely entered the app

**Comment by bmaroti9** [comment]
Oh, that's weird. Than I don't know. Than maybe a lot of people were sending requests at the same time and it blocked everyone for a short amount of time. I'm not sure. We'll just have to see if it pops up again.

**Comment by ak47m91** [comment]
It's been there for a week

**Comment by bmaroti9** [comment]
Wait, you mean it's been consistently like this for a week?

**Comment by ak47m91** [comment]
Bruh, just checked now , it fixed itself

**Comment by ak47m91** [comment]
Sorry for the hastle
