### ISSUE TITLE
Import/Export locations and settings preferences

### ISSUE THREAD

**Issue by serrq** [bmaroti9/Overmorrow#32]
I have several locations.

Is it possible backup/restore them in a zip file?

Also settings preferences if possible, in modular backup manner.

Easily restore in a new device or to send to a friend.

![modular-backup](https://github.com/user-attachments/assets/d7801c75-327b-4717-9aa7-d3ebef350766)

**Comment by bmaroti9** [comment]
I don't think there is a point. With an app that has hundreds of settings, i could see the reason, but Overmorrow only has 10 settings, as of right now, and i think it would take significantly less time to just set your settings and locations manually, than hassling with the exporting them in a zip file. Not even mentioning all the time it would take to build this feature.
