### ISSUE TITLE
App proposal for the developer

### ISSUE THREAD

**Issue by serrq** [bmaroti9/Overmorrow#36]
Hi dev. Are you interested in building a "solid cologne refills manager" app?

Stores

https://theorijin.com/products/aroma-59-fragrance

https://fultonandroark.com/collections/solid-fragrances

https://alfredlane.com/collections/solidcolognes

https://juniperridge.com/collections/perfume-cologne-core

Videos

https://www.youtube.com/watch?v=0IgR5FWjF0Q

https://www.youtube.com/watch?v=JNGKsPy0vr4

https://www.youtube.com/watch?v=mEUyv3hd_ik

Features

• graphical power bar to know exactly how much scent remains (in percentages and in grams)
• refill starting date
• refill ending date
• statistics (solid bar daily consuption, most used fragrances, etc)
• refills library (all fragrances one owns categorized by brand, fragrance, type, scenario, etc.)

![Aroma-59-Reduced_04_19122cb3-1620-43bd-9820-2daa7603a03b_1080x](https://github.com/user-attachments/assets/61c03183-50e1-407c-9dcb-98325174cc34)

![Aroma-59-Reduced_04_1080x](https://github.com/user-attachments/assets/253a101f-2d6d-4c7b-9e3e-132912f47e67)

![Aroma-59-Reduced_05_900x](https://github.com/user-attachments/assets/45f1e9e6-bd9c-4f37-af77-16186e2a9ff5)

![Aroma-59-Reduced-02_1080x](https://github.com/user-attachments/assets/65cbe983-57fd-43c3-9c65-044d458df0c0)

**Comment by bmaroti9** [comment]
No.
