### ISSUE TITLE
missed day in forecast with met norway

### ISSUE THREAD

**Issue by skdubg** [bmaroti9/Overmorrow#38]
Hello, 

I think there is a day missing in the forecast:
Here comes Wednesday right after Monday
![Screenshot_20240928-192019](https://github.com/user-attachments/assets/4b354cd0-c608-4c66-bffc-5337b3c51111)

**Comment by bmaroti9** [comment]
Wow, that's interesting. I see it too. I will look into it. Fortunately it seems like a met-norway problem only.

**Comment by bmaroti9** [comment]
Fixed! It was caused by a timezone offset issue which basically made all the days be offset by 1 day, but the break from 1 hour forecast to 6 hour got it back to the actual date. Anyway i just had to add the timezone offset to the date code.
It's gonna be available in next update.

**Comment by skdubg** [comment]
Many thanks for the effort. 🙂
