### ISSUE TITLE
Option to exclude elements

### ISSUE THREAD

**Issue by VasilisKos** [bmaroti9/Overmorrow#41]
Now there's only the option to rearrange the app's elements. It'd be nice to add the option to choose which elements to be visible, maybe with a + or - button next to each one in the rearrangement list.

**Comment by bmaroti9** [comment]
So I thought this would be much more complicated, but it was surprisingly easy to implement
I also added a reset button, in case something breaks.

https://github.com/user-attachments/assets/557e02c3-acb2-4b2e-9c1a-68baaf157960

**Comment by VasilisKos** [comment]
Perfect! 👍
