### ISSUE TITLE
Option to display dates as dd/mm

### ISSUE THREAD

**Issue by dummycaterpillar** [bmaroti9/Overmorrow#47]
As a setting in "general", perhaps? I know, there's almost zero chance to misunderstand the neatly ordered mm/dd displayed for daily forecasts, but just like how I'm more used to SI units, I'm also more used to seeing dd/mm in daily life at where I'm from.

Thank you for the pretty app.

**Comment by bmaroti9** [comment]
Done!
Should be available with next release.

https://github.com/user-attachments/assets/bf980fd1-f939-492e-8a9e-c741651fdc54

**Comment by bmaroti9** [comment]
available in v2.4.4
