### ISSUE TITLE
When using met norway, the pricip. counter breaks (too many decimal places)

### ISSUE THREAD

**Issue by NotFrants** [bmaroti9/Overmorrow#49]
![Screenshot_20241122-071329.png](https://github.com/user-attachments/assets/7077708e-10ec-437b-b013-a070a949defa)

![Screenshot_20241122-071334.png](https://github.com/user-attachments/assets/ba7f709c-0f49-4a2a-aeb1-5e01b69930cf)

![Screenshot_20241122-071639.png](https://github.com/user-attachments/assets/d1d264c6-f3f9-4599-ad7a-29763cbc2093)

The counter breaks both with millimeters and inches as the unit of measurement, and it remains in inches. I think this is because met norway reports precip. as `[number]in`, and the app fails to round it, and then doesnt reach the line where it adds the unit so it remains the same.

**Comment by NotFrants** [comment]
P.S. I do not live in vatican, I just used it as an example.

**Comment by bmaroti9** [comment]
Wow! this almost always somehow happens with some random precip display. I've never seen it like this so I never thought to round it. Anyway i fixed it, should be in next release.

**Comment by NotFrants** [comment]
Ah yes, exact precipitation.
![Screenshot_20241203-083425.png](https://github.com/user-attachments/assets/44202e21-2674-4f9a-b2fb-382a14b9177f)

@bmaroti9 when is the next release?

**Comment by bmaroti9** [comment]
fixed in v2.4.4
