### ISSUE TITLE
Api keys

### ISSUE THREAD

**Issue by andersfalt** [bmaroti9/Overmorrow#5]
How would you configure your api_key.dart file?

**Comment by andersfalt** [comment]
What api keys are needed for this project?

**Comment by bmaroti9** [comment]
Hi!
Overmorrow has 2 weather providers: open-meteo and weatherapi.
Accessing the open-meteo data doesn't require an api key, but for weatherapi you need a key. I store that key in a file called api_key.dart. For obvious reasons this file hasn't been backed up into github. If you want to configure the file, you just have to create a file called api_key.dart in the lib folder and add this line to it:
const String wapi_Key = "<your-api-key>"  
And then the app will use that for api calls.

Hope this answers your question!

**Comment by bmaroti9** [comment]
I have added an api key example file in the lib folder that shows instructions on how to use your on api key.
