### ISSUE TITLE
Is there any indication of wind direction?

### ISSUE THREAD

**Issue by caoliver** [bmaroti9/Overmorrow#6]
I use the direction of the wind when planning my bike trips.  I.e. make a heavy effort out or on the return.  I see a speed indication, but no compass heading at all.  Am I missing something?

**Comment by bmaroti9** [comment]
Hi!
You are not missing anything. There is no wind direction indicator as of right now. I would like to add it though at some point.

**Comment by caoliver** [comment]
I don't know if the upstream weather services provide gust info or not, but that would be a nice addition too.  I use the QuickWeather app as well, and it too lacks this information.

**Comment by bmaroti9** [comment]
Yes both open-meteo and weatherapi provide gust info so it could be possible to add that as well. But i will need to work and experiment on that, as well as the wind direction.

**Comment by caoliver** [comment]
Great!  If you need a beta tester for something that's beyond the crashing phase, don't hesitate to get in touch.

**Comment by knasiotis** [comment]
I was about to open an issue for the same thing. A wind direction indication would be greatly appreciated. I love this app

**Comment by bmaroti9** [comment]
I have added wind direction indicators for current:
![Screenshot from 2024-05-25 13-41-42](https://github.com/bmaroti9/Overmorrow/assets/101268206/e15c447a-e609-40cf-a0c9-c76b499b6b00)


today, tomorrow, overmorrow:
![Screenshot from 2024-05-25 13-41-50](https://github.com/bmaroti9/Overmorrow/assets/101268206/241bf6bd-b7f8-4575-9182-a09b32753a98)


and daily:
![Screenshot from 2024-05-25 13-41-56](https://github.com/bmaroti9/Overmorrow/assets/101268206/b83aaa1f-7f05-4847-9536-3b9101cae404)

**Comment by bmaroti9** [comment]
I have added them to v2.3.10.
