### ISSUE TITLE
[feature request] Material You 

### ISSUE THREAD

**Issue by deathblade666** [bmaroti9/Overmorrow#9]
Hello, first of all just wanna say amazing work on this thus far. It looks (and works) great! I think your current design would pair very well with the material you framework (and thus this request). Keep up the great work! Not sure what info would be helpful but if there is any additional information I can provide just let me know.

**Comment by bmaroti9** [comment]
Correct me if i'm wrong but isn't material you the ability to set the app theme from the wallpaper? But if it is, doesn't it kind of defeat the mentality of what we have currently, that the app colors are set from the image itself. Am I misunderstanding something here, or do you all think it would look cool if the theme was different from the image color? I don't know, I always liked the way the colors were adapting to the image...

**Comment by bmaroti9** [comment]
I think i have a good idea on how this could be implemented well, but i'll need some time to do it.

I am thinking of adding network fetched images from unsplash. from there i am thinking of adding an option for different color specific themes. so for example you could select purple color mode, and then their would only be purple images and then obviously a purple background to go with the image. after doing this, it could be possible to fetch the material you theme and then match that to the closest color specific theme, therefore fetching images close to your color, and making the background your actual color.

This is still just a concept, but it might just work.
Though i have some concerns, for example finding green colored images for every weather condition will be extremely challenging. And it will probably take a ton of time to build.

**Comment by bmaroti9** [comment]
I don't know why i didn't link it here already. I am working on the material you redesign right now #22.

**Comment by bmaroti9** [comment]
available with the 2.4.1 version
